import {decodeHtmlEntities,decodeJwt,escapeHtml,jsonDiff,makeUuid,markdownToHtml,minifyCss,minifyHtml,regexMatches} from "./p15-tools.js";
import {e,statusLine,copyText} from "./p15-ui-shared.js";

function diffBody(){return `<div class="p15-editor-grid"><label>Eski JSON<textarea id="p15A" class="text-control p15-code">{"name":"Ali","active":true}</textarea></label><label>Yeni JSON<textarea id="p15B" class="text-control p15-code">{"name":"Ali","active":false,"role":"analyst"}</textarea></label></div><div class="action-row"><button class="primary-button" id="p15Run">Karşılaştır</button></div><div id="p15Summary" class="p15-metrics"></div><div id="p15Diff" class="p15-diff"></div>${statusLine("İki JSON nesnesini path bazında karşılaştır.")}`}
function wireDiff(r){const s=r.querySelector("#p15Status");r.querySelector("#p15Run").onclick=()=>{try{const x=jsonDiff(r.querySelector("#p15A").value,r.querySelector("#p15B").value);r.querySelector("#p15Summary").innerHTML=[["Eklenen",x.summary.added],["Silinen",x.summary.removed],["Değişen",x.summary.changed]].map(v=>`<article><span>${v[0]}</span><strong>${v[1]}</strong></article>`).join("");r.querySelector("#p15Diff").innerHTML=x.changes.map(v=>`<article class="${v.type}"><span>${v.type}</span><code>${e(v.path)}</code><small>${e(v.type==="added"?JSON.stringify(v.after):v.type==="removed"?JSON.stringify(v.before):`${JSON.stringify(v.before)} → ${JSON.stringify(v.after)}`)}</small></article>`).join("")||'<div class="p15-good">Fark yok.</div>';s.textContent=x.equal?"JSON içerikleri aynı.":`${x.changes.length} fark bulundu.`}catch(x){s.textContent=`JSON hatası: ${x.message}`}}}

function regexBody(){return `<div class="p15-regex-line"><span>/</span><input id="p15Pattern" class="text-control" value="\\b\\w{4,}\\b" spellcheck="false"><span>/</span><input id="p15Flags" class="text-control" value="gi" maxlength="8"></div><label class="p15-stack">Test metni<textarea id="p15Text" class="text-control p15-code">Merhaba dünya. Regex alanı canlı eşleşmeleri gösterir.</textarea></label><div id="p15Highlight" class="p15-highlight"></div><div id="p15Matches" class="p15-match-list"></div>${statusLine("Pattern, flag veya metni değiştir; sonuç canlı güncellensin.")}`}
function marked(text,ms){let c=0,o="";for(const m of ms){o+=e(text.slice(c,m.index))+`<mark>${e(text.slice(m.index,m.end))||"∅"}</mark>`;c=m.end}return(o+e(text.slice(c))).replaceAll("\n","<br>")}
function wireRegex(r){const p=r.querySelector("#p15Pattern"),f=r.querySelector("#p15Flags"),t=r.querySelector("#p15Text"),s=r.querySelector("#p15Status"),draw=()=>{try{const x=regexMatches(p.value,f.value,t.value);r.querySelector("#p15Highlight").innerHTML=marked(t.value,x.matches);r.querySelector("#p15Matches").innerHTML=x.matches.slice(0,50).map((m,n)=>`<article><span>#${n+1} · ${m.index}-${m.end}</span><strong>${e(m.value||"∅")}</strong><code>${e(m.groups.length?JSON.stringify(m.groups):"capture yok")}</code></article>`).join("");s.textContent=`${x.matches.length} eşleşme · flag: ${x.flags}`+(x.limited?" · ilk 500 sonuç":"")}catch(x){s.textContent=`Regex hatası: ${x.message}`}};[p,f,t].forEach(x=>x.oninput=draw);draw()}

function uuidBody(){return `<div class="p15-ratio-grid"><label>Adet<input id="p15Count" class="text-control" type="number" min="1" max="100" value="10"></label><div class="p15-inline-action"><button class="primary-button" id="p15Run">UUID üret</button><button class="secondary-button" id="p15Copy">Tümünü kopyala</button></div></div><pre id="p15Output" class="p15-uuid-output"></pre>${statusLine("Kriptografik rastgele v4 UUID üret.")}`}
function wireUuid(r){const o=r.querySelector("#p15Output"),s=r.querySelector("#p15Status"),draw=()=>{try{const n=Math.max(1,Math.min(100,+r.querySelector("#p15Count").value||1));o.textContent=Array.from({length:n},()=>makeUuid()).join("\n");s.textContent=`${n} UUID üretildi.`}catch(x){s.textContent=`Hata: ${x.message}`}};r.querySelector("#p15Run").onclick=draw;r.querySelector("#p15Copy").onclick=()=>copyText(r,o.textContent,"UUID listesi kopyalandı.");draw()}

function jwtBody(){return `<label class="p15-stack">JWT<textarea id="p15Input" class="text-control p15-code" placeholder="eyJhbGciOi…"></textarea></label><div class="action-row"><button class="primary-button" id="p15Run">Payload oku</button></div><div class="p15-editor-grid"><div class="result-wrap"><div class="result-head"><span>Header</span></div><pre id="p15Header"></pre></div><div class="result-wrap"><div class="result-head"><span>Payload</span></div><pre id="p15Payload"></pre></div></div><div class="p15-warning">Bu araç yalnızca Base64URL içeriğini okur; imzayı doğrulamaz.</div>${statusLine("JWT metnini yapıştır.")}`}
function wireJwt(r){const s=r.querySelector("#p15Status");r.querySelector("#p15Run").onclick=()=>{try{const x=decodeJwt(r.querySelector("#p15Input").value);r.querySelector("#p15Header").textContent=JSON.stringify(x.header,null,2);r.querySelector("#p15Payload").textContent=JSON.stringify(x.payload,null,2);s.textContent=`Payload okundu · imza ${x.signaturePresent?"mevcut ama doğrulanmadı":"yok"}.`}catch(x){s.textContent=`JWT hatası: ${x.message}`}}}

function mdBody(){return `<div class="p15-editor-grid"><label>Markdown<textarea id="p15Input" class="text-control p15-code"># Başlık\n\n**Kalın** metin ve [bağlantı](https://example.com).\n\n- Bir\n- İki</textarea></label><div><span class="p15-label">Canlı önizleme</span><div id="p15Preview" class="p15-md-preview"></div></div></div><div class="result-wrap"><div class="result-head"><span>HTML</span><button class="text-button" id="p15Copy">Kopyala</button></div><pre id="p15Output"></pre></div>${statusLine("Markdown değiştikçe güvenli HTML önizlemesi güncellenir.")}`}
function wireMd(r){const i=r.querySelector("#p15Input"),o=r.querySelector("#p15Output"),p=r.querySelector("#p15Preview"),draw=()=>{const h=markdownToHtml(i.value);o.textContent=h;p.innerHTML=h};i.oninput=draw;r.querySelector("#p15Copy").onclick=()=>copyText(r,o.textContent,"HTML kopyalandı.");draw()}

function minBody(kind){const l=kind==="html"?"HTML":"CSS",sample=kind==="html"?'<!-- yorum -->\n<div class="card">\n  <strong>Merhaba</strong>\n</div>':'/* yorum */\n.card {\n  padding: 16px;\n  color: #111;\n}';return `<label class="p15-stack">${l}<textarea id="p15Input" class="text-control p15-code">${e(sample)}</textarea></label><div class="action-row"><button class="primary-button" id="p15Run">Temizle ve sıkıştır</button><button class="secondary-button" id="p15Copy">Çıktıyı kopyala</button></div><div class="result-wrap"><div class="result-head"><span>Çıktı</span></div><pre id="p15Output"></pre></div>${statusLine(`${l} girdisini tarayıcıda küçült.`)}`}
function wireMin(r,kind){const o=r.querySelector("#p15Output"),s=r.querySelector("#p15Status"),run=()=>{const a=r.querySelector("#p15Input").value,b=kind==="html"?minifyHtml(a):minifyCss(a);o.textContent=b;s.textContent=`${a.length} → ${b.length} karakter · %${(a.length?Math.max(0,(1-b.length/a.length)*100):0).toFixed(1)} küçülme.`};r.querySelector("#p15Run").onclick=run;r.querySelector("#p15Copy").onclick=()=>copyText(r,o.textContent,"Çıktı kopyalandı.");run()}

function entityBody(){return `<div class="p15-editor-grid"><label>Metin / HTML<textarea id="p15Input" class="text-control p15-code">&lt;button title=&quot;Merhaba&quot;&gt;Başla &amp; devam et&lt;/button&gt;</textarea></label><div class="p15-controls"><button class="primary-button" id="p15Encode">Entity encode</button><button class="secondary-button" id="p15Decode">Entity decode</button><button class="secondary-button" id="p15Copy">Çıktıyı kopyala</button></div></div><div class="result-wrap"><div class="result-head"><span>Çıktı</span></div><pre id="p15Output"></pre></div>${statusLine("HTML özel karakterlerini güvenli entity biçimine çevir veya çöz.")}`}
function wireEntity(r){const i=r.querySelector("#p15Input"),o=r.querySelector("#p15Output"),s=r.querySelector("#p15Status");r.querySelector("#p15Encode").onclick=()=>{o.textContent=escapeHtml(i.value);s.textContent="HTML entity çıktısı hazır."};r.querySelector("#p15Decode").onclick=()=>{o.textContent=decodeHtmlEntities(i.value);s.textContent="Entity değerleri çözüldü."};r.querySelector("#p15Copy").onclick=()=>copyText(r,o.textContent,"Çıktı kopyalandı.")}

const V={"json-diff":{body:diffBody,wire:wireDiff},"regex-playground":{body:regexBody,wire:wireRegex},"uuid-generator":{body:uuidBody,wire:wireUuid},"jwt-reader":{body:jwtBody,wire:wireJwt},"markdown-html":{body:mdBody,wire:wireMd},"html-minify":{body:()=>minBody("html"),wire:r=>wireMin(r,"html")},"css-minify":{body:()=>minBody("css"),wire:r=>wireMin(r,"css")},"html-entities":{body:entityBody,wire:wireEntity}};
export const getP15View=mode=>V[mode];
