const NOTES_KEY="kisiselaraclar:p16:notes";
const TASKS_KEY="kisiselaraclar:p16:tasks";
const LOCAL_CHANGE="kisiselaraclar:local-change";
const UI_RENDER="kisiselaraclar:ui-rendered";
const NOTE_ICON='<svg viewBox="0 0 24 24"><path d="M6 4h9l3 3v13H6z"/><path d="M15 4v4h4"/><path d="M9 12h6M9 16h5"/></svg>';
const TASK_ICON='<svg viewBox="0 0 24 24"><rect x="4" y="4" width="16" height="16" rx="4"/><path d="m8.5 12 2.2 2.2 4.8-5"/></svg>';
const PLUS_ICON='<svg viewBox="0 0 24 24"><path d="M12 5v14M5 12h14"/></svg>';
let timer=0,sheet=null;
function store(){try{return localStorage}catch{return null}}
function arr(key){try{const v=JSON.parse(store()?.getItem(key)||"[]");return Array.isArray(v)?v:[]}catch{return[]}}
function save(key,value){try{store()?.setItem(key,JSON.stringify(value));globalThis.dispatchEvent(new CustomEvent(LOCAL_CHANGE,{detail:{key}}));return true}catch{return false}}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function compact(v,n=70){const t=String(v??"").replace(/\s+/g," ").trim();return t.length>n?`${t.slice(0,n-1)}…`:t}
function today(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function id(p){return `${p}-${Date.now().toString(36)}-${globalThis.crypto?.randomUUID?.()||Math.random().toString(36).slice(2)}`}
function dateText(){try{return new Intl.DateTimeFormat("tr-TR",{weekday:"long",day:"numeric",month:"long"}).format(new Date())}catch{return today()}}
function shortDate(v){try{return new Intl.DateTimeFormat("tr-TR",{day:"numeric",month:"short"}).format(new Date(`${v}T12:00:00`))}catch{return v}}
function timeText(v){try{return v?new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit"}).format(new Date(v)):""}catch{return""}}
function notes(){return arr(NOTES_KEY).filter(Boolean).map(x=>({...x,id:String(x.id||id("note")),title:String(x.title||""),text:String(x.text||""),kind:x.kind==="voice"?"voice":"written",updatedAt:Number(x.updatedAt)||0})).sort((a,b)=>b.updatedAt-a.updatedAt)}
function tasks(){return arr(TASKS_KEY).filter(x=>x&&String(x.title||"").trim()).map(x=>({...x,id:String(x.id||id("task")),title:String(x.title||"").trim(),date:/^\d{4}-\d{2}-\d{2}$/.test(String(x.date||""))?String(x.date):"",time:/^\d{2}:\d{2}$/.test(String(x.time||""))?String(x.time):"",done:Boolean(x.done),updatedAt:Number(x.updatedAt)||Date.now()}))}
function summary(){const d=today(),ns=notes(),ts=tasks(),open=ts.filter(x=>!x.done),todayAll=ts.filter(x=>x.date===d).sort((a,b)=>(a.time||"99:99").localeCompare(b.time||"99:99")),over=open.filter(x=>x.date&&x.date<d).sort((a,b)=>a.date.localeCompare(b.date));return{d,ns,ts,todayAll,todayOpen:todayAll.filter(x=>!x.done),todayDone:todayAll.filter(x=>x.done),over,focus:[...over.map(x=>({...x,state:"Gecikti"})),...todayAll.filter(x=>!x.done).map(x=>({...x,state:"Bugün"}))].slice(0,6)}}
function taskRows(s){if(!s.focus.length)return'<button class="p37-empty" data-tool="tasks-calendar" data-tool-action="new-task" type="button">Bugün için açık iş yok · görev ekle →</button>';return s.focus.map(x=>`<label class="p37-task ${x.state==="Gecikti"?"is-overdue":""}"><input type="checkbox" data-p37-task="${esc(x.id)}"><span class="p37-check"></span><span class="p37-task-copy"><strong>${esc(x.title)}</strong><small>${x.state==="Gecikti"?`Gecikti · ${esc(shortDate(x.date))}${x.time?` · ${esc(x.time)}`:""}`:(x.time?esc(x.time):"Bugün")}</small></span></label>`).join("")}
function noteRows(s){if(!s.ns.length)return'<button class="p37-empty" data-p37-jump="note" type="button">Henüz not yok · ilk notunu ekle →</button>';return s.ns.slice(0,4).map(x=>`<button class="p37-note" data-tool="quick-note" data-tool-action="note:${esc(x.id)}" type="button"><span class="p37-note-icon">${NOTE_ICON}</span><span class="p37-note-copy"><strong>${esc(x.title||compact(x.text,44)||"Adsız not")}</strong><small>${esc(compact(x.text,68)||"Not")}</small></span><time>${esc(timeText(x.updatedAt))}</time></button>`).join("")}
function markup(s){const total=s.todayAll.length,done=s.todayDone.length,p=total?Math.round(done/total*100):0,headline=s.over.length?`${s.over.length} geciken · ${s.todayOpen.length} bugün`:s.todayOpen.length?`${s.todayOpen.length} iş bugün`:"Günün açık";return`<div class="p37-dashboard"><header class="p37-head"><div><h2>Bugün</h2><p>${esc(headline)}</p></div><time>${esc(dateText())}</time></header><div class="p37-grid"><section class="p37-card p37-capture"><div class="p37-card-head"><div><span>Hızlı ekle</span><h3>Aklındakini kaybetme.</h3></div></div><div class="p37-tabs" role="tablist"><button class="is-active" data-p37-mode="note">Not</button><button data-p37-mode="task">Görev</button><button data-p37-mode="voice">Ses</button></div><div class="p37-pane" data-p37-pane="note"><form id="p37NoteForm"><textarea id="p37NoteInput" rows="3" placeholder="Bir şey yaz…"></textarea><div class="p37-actions"><small>Bugüne eklenir</small><button>Kaydet</button></div></form></div><div class="p37-pane" data-p37-pane="task" hidden><form id="p37TaskForm"><input id="p37TaskInput" placeholder="Ne yapılacak?" autocomplete="off"><div class="p37-task-meta"><input id="p37TaskDate" type="date" value="${s.d}"><input id="p37TaskTime" type="time"><button>Ekle</button></div></form></div><div class="p37-pane" data-p37-pane="voice" hidden><div class="p37-actions"><small>Konuşarak not almak için sesli yazmayı aç.</small><button type="button" data-tool="voice-note">Sesli yazmayı aç</button></div></div></section><section class="p37-card"><div class="p37-card-head"><div><span>Odak</span><h3>Bugünün işleri</h3></div><button class="p37-link" data-tool="tasks-calendar" type="button">Tümü →</button></div><div class="p37-progress"><span><strong>${done}</strong> / ${total||0} tamamlandı</span><i><b style="width:${p}%"></b></i></div><div class="p37-list">${taskRows(s)}</div></section></div><section class="p37-card"><div class="p37-card-head"><div><span>Yakın zamanda</span><h3>Son notlar</h3></div><button class="p37-link" data-tool="quick-note" type="button">Tümü →</button></div><div class="p37-list">${noteRows(s)}</div></section><div class="p37-shortcuts"><button data-tool="quick-note" type="button">${NOTE_ICON}<span>Notlar</span></button><button data-tool="tasks-calendar" type="button">${TASK_ICON}<span>Görevler</span></button><button data-tool="meeting-notes" type="button"><svg viewBox="0 0 24 24"><path d="M5 5h14v11H9l-4 3z"/><path d="M8 9h8M8 12h5"/></svg><span>Toplantı</span></button></div></div>`}
function setMode(w,mode,focus=false){w.querySelectorAll("[data-p37-mode]").forEach(b=>b.classList.toggle("is-active",b.dataset.p37Mode===mode));w.querySelectorAll("[data-p37-pane]").forEach(p=>{const on=p.dataset.p37Pane===mode;p.hidden=!on});if(focus)requestAnimationFrame(()=>w.querySelector(mode==="task"?"#p37TaskInput":mode==="note"?"#p37NoteInput":'[data-tool="voice-note"]')?.focus())}
function render(w){if(!(w instanceof HTMLElement))return;w.dataset.p37Owner="true";w.className="p17-workspace p37-workspace";const s=summary();w.innerHTML=markup(s);wire(w);document.documentElement.dataset.visualSystem="p37"}
function wire(w){w.querySelectorAll("[data-p37-mode]").forEach(b=>b.onclick=()=>setMode(w,b.dataset.p37Mode,true));w.querySelectorAll("[data-p37-jump]").forEach(b=>b.onclick=()=>setMode(w,b.dataset.p37Jump,true));w.querySelector("#p37NoteForm")?.addEventListener("submit",e=>{e.preventDefault();const i=w.querySelector("#p37NoteInput"),v=String(i?.value||"").trim();if(!v)return i?.focus();const ns=notes();ns.unshift({id:id("note"),title:compact(v,46),text:v,kind:"written",pinned:false,completed:false,noteDate:today(),updatedAt:Date.now()});if(save(NOTES_KEY,ns))render(w)});w.querySelector("#p37TaskForm")?.addEventListener("submit",e=>{e.preventDefault();const i=w.querySelector("#p37TaskInput"),v=String(i?.value||"").trim();if(!v)return i?.focus();const ts=tasks();ts.push({id:id("task"),title:v,date:String(w.querySelector("#p37TaskDate")?.value||today()),time:String(w.querySelector("#p37TaskTime")?.value||""),done:false,createdAt:Date.now(),updatedAt:Date.now()});if(save(TASKS_KEY,ts))render(w)});w.querySelectorAll("[data-p37-task]").forEach(i=>i.onchange=()=>{const key=String(i.dataset.p37Task||"");if(save(TASKS_KEY,tasks().map(x=>x.id===key?{...x,done:i.checked,updatedAt:Date.now()}:x)))render(w)})}
function enhanceHome(){document.querySelectorAll("#homeView #p17Workspace,#desktopHomeView #p17Workspace").forEach(w=>{if(w.dataset.p37Owner!=="true")render(w)})}
function enhanceTools(){const tv=document.querySelector("#toolView");if(!tv)return;const note=tv.querySelector(".p16-note-layout");if(note){const p=note.closest(".tool-panel")||tv;p.classList.add("p37-note-panel");const h=p.querySelector(".tool-title-row h2");if(h&&h.textContent!=="Not")h.textContent="Not";const t=p.querySelector("#p16NoteTitle");if(t)t.placeholder="Başlık"}const task=tv.querySelector(".p16-task-layout");if(task){const p=task.closest(".tool-panel")||tv;p.classList.add("p37-task-panel");const h=p.querySelector(".tool-title-row h2");if(h&&h.textContent!=="Görevler")h.textContent="Görevler"}const voice=tv.querySelector(".p16-voice");if(voice){const p=voice.closest(".tool-panel")||tv;p.classList.add("p37-voice-panel");const h=p.querySelector(".tool-title-row h2");if(h&&h.textContent!=="Sesli not")h.textContent="Sesli not"}}
function closeSheet(){sheet?.classList.remove("is-open")}
function jump(mode){closeSheet();document.querySelector('#mobileDock [data-mobile-action="today"]')?.click();let n=0;const go=()=>{const w=document.querySelector("#homeView #p17Workspace,#desktopHomeView #p17Workspace");if(w?.dataset.p37Owner==="true"){setMode(w,mode,true);w.querySelector(".p37-capture")?.scrollIntoView({behavior:"smooth",block:"center"});return}if(++n<10)setTimeout(go,60)};setTimeout(go,30)}
function ensureSheet(){if(sheet?.isConnected)return sheet;sheet=document.createElement("div");sheet.className="p37-sheet";sheet.innerHTML=`<button class="p37-sheet-bg" aria-label="Kapat"></button><div class="p37-sheet-card"><strong>Hızlı ekle</strong><button data-mode="note">Not</button><button data-mode="task">Görev</button><button data-mode="voice">Ses</button></div>`;document.body.append(sheet);sheet.querySelector(".p37-sheet-bg").onclick=closeSheet;sheet.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>jump(b.dataset.mode));return sheet}
function setDockText(d,action,text){const node=d.querySelector(`[data-mobile-action="${action}"] strong`);if(node&&node.textContent!==text)node.textContent=text}
function enhanceDock(){const d=document.querySelector("#mobileDock");if(!d)return;setDockText(d,"today","Bugün");setDockText(d,"note","Notlar");setDockText(d,"task","Görevler");if(d.querySelector(".p37-dock-add"))return;const b=document.createElement("button");b.type="button";b.className="p37-dock-add";b.setAttribute("aria-label","Hızlı ekle");b.innerHTML=`<span class="p37-dock-plus">${PLUS_ICON}</span><strong>Ekle</strong>`;d.insertBefore(b,d.querySelector('[data-mobile-action="task"]'));b.onclick=()=>ensureSheet().classList.add("is-open")}
function enhance(){enhanceHome();enhanceTools();enhanceDock()}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>requestAnimationFrame(enhance),0)}
globalThis.addEventListener(UI_RENDER,schedule);globalThis.addEventListener("kisiselaraclar:remote-change",()=>document.querySelectorAll("#homeView #p17Workspace[data-p37-owner='true'],#desktopHomeView #p17Workspace[data-p37-owner='true']").forEach(render));document.readyState==="loading"?document.addEventListener("DOMContentLoaded",schedule,{once:true}):schedule();
